### ISSUE TITLE
Any options for inline attachments MailgunAdopter

### ISSUE THREAD

**Issue by ijunaid8989** [beam-community/bamboo#430]
In past, we were using mailgun wrapper https://github.com/evercam/mailgun/commit/8c73ada08137ce875b487949167d60fecb1715dc and added inline attachment options by ourselves.

Now we are planning to switch to Bamboo, and I have done formal emails method conversion from mailgun to bamboo mailgun adopter but it's not sending inline attachments, Is there any option for that in bamboo? 

For emails like 

![image](https://user-images.githubusercontent.com/13561999/45094751-a423e900-b135-11e8-84e3-e862abcf7bfe.png)

Instead of showing image as mentioned in template.

```html
<img src="cid:snapshot.jpg" alt='Last Snapshot' style="width: 100%; display:block; margin:0 auto;">
```

its just showing it alt text. and in the bottom it attached the snapshot. I am sorry if that is not the right place to ask this. I have tried in Elixir Slack channel but no one is interested to answer.

**Comment by germsvel** [comment]
Hi @ijunaid8989 thanks so much for opening the issue and for the patience! I'm just starting to maintain Bamboo and trying to look through the open issues. 

This seems related to https://github.com/thoughtbot/bamboo/issues/502. It seems like it might be good to allow people to set the `content_disposition` and then map that to the adapters as needed. 

If this is still something of interest, let me know. I'll try to get to it, or if you're up for it, I'd be happy to review a PR.
