### ISSUE TITLE
assert_email_delivered_with not working with multiple emails

### ISSUE THREAD

**Issue by atomkirk** [beam-community/bamboo#433]
If I do 

```
{:messages, messages} = Process.info(self(), :messages)

for {:delivered_email, email} <- messages do
  email
end
```

the email clearly appears in the list, but if I do:

```
assert_email_delivered_with(subject: "subject")
```

it fails and prints a list without the email… I know for absolute certain the email is being sent and with the matching subject. I used the first snippet to write a test that works, but I figured this could be fixed

I assumed this is an issue when multiple emails get sent? Maybe it would work if only one was sent?

UPDATE: I commented out the code that sends the first email and now it passes. So indeed, this breaks when the email being looked for is not the first (or only?) email being sent

**Comment by jasonandrewduncan** [comment]
Very similar issues. If code sends out multiple emails then assert_delivered_email doesn't seem to match any email I pass in. I my case the code send out an email to an external email address and a separate one to an internal as part of 1 operation.

**Comment by ruudk** [comment]
I'm having the same issue. I need to put the `assert_email_delivered_with` calls in the same order as the emails are being send. That is annoying, because for my integration test I don't know the ordering up front.

I would like to try and see if I can fix this. What would be the best approach to do this? Is this even possible? @germsvel If you could give some hints, I might be able to produce a PR. I'm an Elixir newbie.

**Comment by germsvel** [comment]
Hi @ruudk, thanks for the ping on this. I don't know that there is an easy fix to this. I took a peak at the implementation, and like other comments in this issue mention, we're using `assert_receive` which is grabbing the first email out and making sure the fields in that email match the fields we expect (like `from: "someone"`). 

I think we could probably come up with a better implementation but it would be more complicated. I have to think about it a little bit before I can speak intelligently about it. Is there a workaround that you have in the meantime?

**Comment by ruudk** [comment]
I decided to do it like this instead:
```elixir
      assert_received(
        {:delivered_email,
         %Bamboo.Email{
           subject: "SubjectPrefix1" <> rest
         }}
      )

      assert_received(
        {:delivered_email,
         %Bamboo.Email{
           subject: "SubjectPrefix2" <> rest
         }}
      )
```

This way, it uses Elixir pattern matching instead. It works.

**Comment by germsvel** [comment]
@ruudk yes! That's exactly what I'd like us to do in `assert_email_delivered_with`, but it's tough to know which parts to pattern match on. Or at least, I haven't thought it through enough. I'm glad you found that workaround for now. But I'll keep thinking about this. If you find a generic way to implement that, I'd love to hear it!
