### ISSUE TITLE
(feature) Support multiple tags for Mailgun

### ISSUE THREAD

**Issue by mstratman** [beam-community/bamboo#492]
I added a `MailgunHelper` with 
 a `tag` function (https://github.com/thoughtbot/bamboo/pull/490), but it currently only supports a single tag. 
([aa4a22](https://github.com/thoughtbot/bamboo/pull/490/commits/aa4a22956485642c93b47e108c3ffd7277aa5125#diff-312afa3cc0acebd25b646fb75f9c5878R18))

I believe https://github.com/thoughtbot/bamboo/issues/469 is a prerequisite. As far as I can tell, Mailgun only supports multiple tags via multiple `o:tag` values

**Comment by a12e** [comment]
#469 is indeed a prerequisite because the headers are stored as a map in %Email{}, meaning each key is unique.
