### ISSUE TITLE
Batch rendering/sending

### ISSUE THREAD

**Issue by brianbolnick** [beam-community/bamboo#503]
I’ve been checking through the docs and haven’t seen anything related to rendering or sending large batches of emails asynchronously. We are sending tens to hundreds of thousands of emails at a time and this would be a big performance win for us if it were possible.

**Comment by germsvel** [comment]
HI @brianbolnick, thanks for opening this issue. I'm taking over maintenance of Bamboo, so I'm trying to get through all the open issues. 

I like the idea of batch sending emails. I'm curious about your thoughts on whether we'd rely on the email providers having APIs to send batches of emails or whether bamboo itself would have some way of batching the emails. 

I'm also curious, what do you mean by batch rendering? Is that something you're currently doing in your app? Do you have any other thoughts on what might be a good solution for this?
