### ISSUE TITLE
Serve SentEmailViewer static assets from a plug instead of CDN

### ISSUE THREAD

**Issue by seivan** [beam-community/bamboo#517]
Seems like [`normalize.css`](https://github.com/thoughtbot/bamboo/tree/master/lib/bamboo/plug/sent_email_viewer) is served from some CDN. I'm a bit uncomfortable with having assets that we don't control, it would be nice if there was an opt in feature to allow us to serve that ourselves from a custom plug

Maybe there could be a config like: 
```elixir
config :my_app, MyApp.Mailer,
  adapter: Bamboo.LocalAdapter
  assets: "static"
```

Then you could just serve the file from `/priv/static` with a plug: 
```elixir
plug Plug.Static,
  at: "/assets/", from: :api, gzip: true,
  only: ~w(css fonts images js favicon.ico robots.txtn)
```

I don't mind wiring up a PR for this, if it's acceptable.

**Comment by germsvel** [comment]
Hi @seivan, I think this optional configuration could make sense and we can fallback to the CDN. It would be nice for it to work out of the box without configuration. Of course if you don't add normalize, then the preview emails might look different or slightly broken. I'm not actually sure to what extent the preview styles rely on normalize.css.
