### ISSUE TITLE
SentEmailViewer should work with with all adapters. 

### ISSUE THREAD

**Issue by seivan** [beam-community/bamboo#518]
It would be nice if `SentEmailViewer` still worked with other adapters, maybe `LocalAdapter` could be an add-on and not just the only one used. 

The rational is that we're using SES Mailbox Simulator for non prod environments, and would love to be able to use it while still having access to the `SentEmailViewer`. 

My suggestion is that `LocalAdapter` should not be a replacement for an actual adapter, but an addition.

Is this something that's acceptable? In which case I don't mind setting up a PR for it.

**Comment by germsvel** [comment]
Thanks for mentioning this @seivan . I'm not a 100% sure, but I think you could make this work already _as is_ by using [Bamboo.SentEmail](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/sent_email.ex)? That's what the `LocalAdapter` uses, right? 

So if you wrote your own adapter that uses `SentEmail` to store and fetch the emails, then you might be good to go? I know that's technically internal workings of `LocalAdapter` and `SentEmailViewer` and thus liable to change, so it might be good to make it official somehow. But for now, would that solve your problem?
