### ISSUE TITLE
Content ID specified with attachment is not sent with message

### ISSUE THREAD

**Issue by dabaer** [beam-community/bamboo#577]
Hello,

I'm attempting to get CID working with emails sent using the SMTP adapter, however when I attach a logo for example

`put_attachment(%Bamboo.Attachment{filename: "logo.png", data: logo, content_type: "image/png", content_id: "headlogo"})`

the content ID i specified does not get sent with the message:

```
Content-Type: image/png; name="logo.png"
Content-Disposition: attachment; filename="logo.png"
Content-Transfer-Encoding: base64
X-Attachment-Id: 3318558395
```

From the documentation i've read with both Bamboo and Bamboo SMTP this would seem like the correct way for me to specify a CID, however it does appear on the email client side.

What is the correct way to achieve this?

**Comment by germsvel** [comment]
Hi @dabaer, thanks for opening this issue. I believe the setting of the content ID would be something that the adapter needs to handle. When you say the SMTP adapter, I'm guessing you mean https://github.com/fewlinesco/bamboo_smtp, right? 

If that's the case, I think you might have to open an issue in that repo. At a quick glance, it seems like that there is a case when that adapter sets the content-id, though I don't know if that would be sufficient for your case. See [this line](https://github.com/fewlinesco/bamboo_smtp/blob/2c2643e1243b6fd3776ef837cda8504787fd2936/lib/bamboo/adapters/smtp_adapter.ex#L237), which was added in [this commit](https://github.com/fewlinesco/bamboo_smtp/commit/97e1dbdebb19192725b03872a9c5cfe5fa1bccef).
