### ISSUE TITLE
How to implement DKIM

### ISSUE THREAD

**Issue by sooonism** [beam-community/bamboo#630]
I want to implement DKIM in the config, But cannot find a proper document.

**Comment by ToshiDK** [comment]
I want to do a CIRS-seq analysis and I am doing rf-count-genome, but the job is not finished after three days.
”rf-count-genome -m -p 64 -wt 64 -r -o ./XXX -fh -f genome.fa XX.bam”

The outfile has
[+] Making output directory...
[+] Guessing file types:

  Sample          Type    5'-end trimming    Library type

XX   BAM     Ignored            unstranded

[+] Importing chromosomes from reference, and building count table base structure...
[+] Inspecting SAM/BAM file headers...
[+] Assuming that provided SAM/BAM files are already sorted. Skipping sorting...
[+] Calculating per-base mutation counts and coverage. This may take a while...
[-] Processing sample "XXXX" (PID: 26829)
