### ISSUE TITLE
deliver_later spec

### ISSUE THREAD

**Issue by bernardo-martinez** [beam-community/bamboo#661]
Hey!

Small issue:
The `deliver_later` spec [here](https://github.com/beam-community/bamboo/blob/main/lib/bamboo/mailer.ex#L85) says that it can return a `String.t()` but looking at the two strategies I see it is not possible, I am missing something?

**Comment by doomspork** [comment]
@bernardo-martinez the validation functions can rename `{:error, String.t()}` The spec is `{:error, Exception.t() | String.t()}` suggesting the second element in the tuple can be a string or an exception.

Here we return `{:error, String.t()}` make the spec valid: https://github.com/beam-community/bamboo/blob/main/lib/bamboo/mailer.ex#L316
