### ISSUE TITLE
Get bamboo_phoenix under beam-community as well?

### ISSUE THREAD

**Issue by stefannibrasil** [beam-community/bamboo#670]
Hello, everyone! I am creating this issue because thoughtbot wants to know if you're also interested in getting https://github.com/thoughtbot/bamboo_phoenix transferred to the beam community as well. We're looking for new codeowners to have it transferred to. I am aware bamboo got transferred a while ago (thank you for that!), so hopefully you also have the capacity of taking bamboo_phoenix as well? :)

**Comment by doomspork** [comment]
Howdy @stefannibrasil! I responded to your email this afternoon. Let's do it!

**Comment by stefannibrasil** [comment]
Awesome, thank you for getting back to me @doomspork. I will close this and follow up via email 🎉

**Comment by doomspork** [comment]
Sounds good @stefannibrasil!
